# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.1.0
group=com.msg.library
java_version=25

# Common
minecraft_version=26.1
mod_name=MSG
mod_author=MikeStorm03
mod_id=msg_library
license=MPL2.0
description=The MSG of contents making... FUIYOH~\nA mod with data driven with some custom that help me and hopefully other content creators out there making content easier

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric
fabric_version=0.145.1+26.1
fabric_loader_version=0.19.3
minecraft_fabric_version_range=>=26.1

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)
minecraft_neoforge_version_range=[26.1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
